### ISSUE TITLE
Error on new version of pf2e system

### ISSUE THREAD

**Issue by AnkeKatomeky** [oWave/pf2e-flatcheck-helper#23]
Emanation Automation function break emanation base spell window(SpellSheetPF2e). In web console is error:

```
Error: An error occurred while rendering SpellSheetPF2e 35. e.isOfType is not a function
[Detected 2 packages: pf2e-flatcheck-helper(0.12.4), system:pf2e(6.8.0)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.js:5795:13Caused by: TypeError: e.isOfType is not a function
[Detected 2 packages: pf2e-flatcheck-helper(0.12.4), system:pf2e(6.8.0)]
    at emanation.ts:79:6
    at Array.filter (<anonymous>)
    at extractEffects (emanation.ts:78:81)
    at async spellSheetRenderInner (emanation.ts:115:18)
    at async SpellSheetPF2e.spellSheetRenderWrapper (emanation.ts:165:49)
    at async SpellSheetPF2e._render (foundry.js:5844:19)
    at async SpellSheetPF2e._render (foundry.js:6572:5)
    at async SpellSheetPF2e._render (foundry.js:7158:5)
    at async maintainFocusInRender (pf2e.mjs:1341:292803)
    at async SpellSheetPF2e._render (pf2e.mjs:1607:58129)
```

**Comment by oWave** [comment]
Oddly enough not caused by the system update, just something I should have caught way earlier: If the spell's description contains a UUID that doesn't point to an item, my code breaks.
Fixed that just now, and also made sure any future errors won't completely break the spell sheet.
